Month 7 / step 1
foxriver660/react-burger pull request #1
Opened 2022-11-26 10:16 UTC by foxriver660

2022-11-26 11:02 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;

### **Но есть несколько замечаний, которые нужно исправить:**

- В компоненте App-header требуется поправить семантику, переделать кнопки в ссылки.

  Оберните иконку и текст в шапке в ссылку `<a href="/#">`

- По макету (BurgerConstructor): Скроллится должен только контент, булки должны быть на месте.

- В BurgerConstructor булки должны быть одинаковыми.

- Поправьте работу с propTypes (отметил места в коде).

### **Сделает код лучше:**

- При клике на соответствующий таб должен происходить скролл к нужному разделу в списке ингредиентов.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-11-26 11:02 UTC, ArslanMustafin commented on src/components/App/App.jsx
> +});
**Можно лучше:**

во многих компонентах дублируется описание PropTypes ингредиента
Лучше вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать

2022-11-26 11:02 UTC, ArslanMustafin commented on src/components/App/App.jsx
> +};
**Надо исправить:**

Замечание пусть и не критичное, но лучше чтобы propTypes были рядом с тем компонентом, которого они описывают.

2022-11-26 11:02 UTC, ArslanMustafin commented on src/components/AppHeader/AppHeader.jsx
> +{
**Можно лучше:**

Лучше удалить, ну или закомментировать полностью, а то скобки не закомментированы.

2022-11-26 11:02 UTC, ArslanMustafin commented on src/components/App/App.jsx
> +  data: PropTypes.arrayOf(itemPropTypes).isRequired,
**Надо исправить:**
Здесь и далее.

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.
Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

2022-11-26 11:02 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  const [dataAPI, setDataAPI] = React.useState(data);
**Надо исправить:**

Не следует использовать useState, если вы не собирайтесь менять переменную.

2022-11-26 11:02 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +            if (index === 0) {
**Надо исправить:**

Делайте фильтрацию до `jsx`. Например: можно отделить булки и ингредиенты, используя методы `find` и `filter`.

```js
const bun = data.find(/** ищем по типу */)
const ingredients = data.filter(/** по типу не равным bun */)
```

И да, булки должны быть одинаковыми, поэтому тут можно легко использовать метод find по типу, на первых этапах.

2022-11-26 11:02 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +                    text={item.name}
**Надо исправить:**

Здесь и ниже.

По макету у булок должны быть надписи `(верх) и (низ)`.

2022-11-26 11:02 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  const [dataAPI, setDataAPI] = React.useState(data);
**Надо исправить:**

Похожее замечание в `burgerConstructor`.

2022-11-26 11:02 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  }, [dataAPI]);
**Можно лучше:**

Лучше использовать useMemo (Знаю, что вы возможно его не знаете, но будет полезно узнать что-то новое). в данном случае useEffect, не оптимальное решение)

2022-11-26 11:02 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +        </ul>
**Можно лучше:**

у каждой категории ингредиентов дублируется верстка, лучше вынести отдельный компонент ingredients-category и переиспользовать его

2022-11-26 11:02 UTC, ArslanMustafin commented on src/components/CustomScrollBar/CustomScrollBar.jsx
> +  const [state, setState] = React.useState(props.side);
**Надо исправить:**

Похожее замечание есть в burgerConstructor.

2022-11-26 11:02 UTC, ArslanMustafin commented on src/components/CustomScrollBar/CustomScrollBar.jsx
> +const CustomScrollBar = ({ children, style, ...props }) => {
**Надо исправить:**

для этого компонента так же нужно описать PropTypes.

2022-11-26 11:02 UTC, ArslanMustafin commented on src/components/CustomScrollBar/CustomScrollBar.jsx
> +          }}
**Можно лучше:** Вообще это критическое замечание, но т.к. вы только начинаете познавать реакт, то просто отмечу его, чтобы в будущем вы знали, что инлайн стили нужно стараться избегать.

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2022-11-26 11:02 UTC, ArslanMustafin commented on src/components/CustomScrollBar/CustomScrollBar.jsx
> +      autoHeightMax={800}
**Надо исправить:**

Нужно вынести в константу, имена констант принято записывать в стиле UPPER_CASE.

2022-11-26 11:02 UTC, ArslanDev666 commented on src/components/IngredientCard/IngredientCard.jsx
> +const IngredientCard = ({ name, _id, type, price, image }) => {
**Надо исправить:**

для этого компонента так же нужно описать PropTypes.

**Можно лучше:**

не стоит разбивать объект ингредиента на мелкие части, лучше передавать целиком и использовать поля объекта.

2022-11-26 11:02 UTC, ArslanDev666 commented on src/index.js
> +    <App />
**Надо исправить:**

Верните StrictMode, он помогает вам отлавливать ошибки.

2022-11-26 11:53 UTC, foxriver660 commented on src/components/App/App.jsx
> +});
done

2022-11-26 11:53 UTC, foxriver660 commented on src/components/App/App.jsx
> +};
done

2022-11-26 11:53 UTC, foxriver660 commented on src/components/AppHeader/AppHeader.jsx
> +{
done

2022-11-26 11:59 UTC, foxriver660 commented on src/components/App/App.jsx
> +  data: PropTypes.arrayOf(itemPropTypes).isRequired,
done

2022-11-26 12:00 UTC, foxriver660 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  const [dataAPI, setDataAPI] = React.useState(data);
done

2022-11-26 12:26 UTC, foxriver660 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +            if (index === 0) {
done

2022-11-26 12:29 UTC, foxriver660 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +                    text={item.name}
done

2022-11-26 12:31 UTC, foxriver660 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  const [dataAPI, setDataAPI] = React.useState(data);
done

2022-11-26 12:32 UTC, foxriver660 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  }, [dataAPI]);
done

2022-11-26 12:49 UTC, foxriver660 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +        </ul>
done

2022-11-26 12:51 UTC, foxriver660 commented on src/components/CustomScrollBar/CustomScrollBar.jsx
> +  const [state, setState] = React.useState(props.side);
done

2022-11-26 13:07 UTC, foxriver660 commented on src/components/CustomScrollBar/CustomScrollBar.jsx
> +const CustomScrollBar = ({ children, style, ...props }) => {
done

2022-11-26 13:11 UTC, foxriver660 commented on src/index.js
> +    <App />
done

2022-11-26 15:18 UTC, foxriver660 commented on src/components/IngredientCard/IngredientCard.jsx
> +const IngredientCard = ({ name, _id, type, price, image }) => {
done

2022-11-26 15:19 UTC, foxriver660 commented on src/components/CustomScrollBar/CustomScrollBar.jsx
> +      autoHeightMax={800}
done

2022-11-28 02:50 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Приступайте к выполнению финального этапа задания.**

- Все замечания с прошлого ревью были исправлены.

### **Сделает код лучше:**

- немного уменьшить высоту блоков) чтобы не скроллить половину экрана для того, чтобы увидеть вторую булку.

- При клике на соответствующий таб должен происходить плавный скролл к нужному разделу в списке ингредиентов.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-11-28 02:50 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +        <img className="pl-2 pr-10" src={bigCurrencyIcon} />
**Надо исправить:**

у элемента `img`, должен быть атрибут `alt`.

2022-11-28 02:50 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  React.useMemo(() => {
**Можно лучше:**

конечно можно и так это делать, но я имел ввиду немного другое)) 

```js
  const { buns, mains, sauces } = useMemo(() => {
    return data.reduce(
      (acc, ingredient) => {
        switch (ingredient.type) {
          case "bun":
            acc.buns.push(ingredient);
            break;
          case "main":
            acc.mains.push(ingredient);
            break;
          case "sauce":
            acc.sauces.push(ingredient);
            break;
          // no default
        }
        return acc;
      },
      { buns: [], mains: [], sauces: [] }
    );
  }, [data]);
```

2022-11-28 02:50 UTC, ArslanDev666 commented on src/components/IngredientCard/IngredientCard.jsx
> +};
**Надо исправить:**

Вы немного не так описали пропсы, вам нужно либо поменять описание тут, либо поменять пропсы, и передавать не несколько полей, а просто 1 объект ингредиента.

2022-11-28 09:11 UTC, foxriver660 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  React.useMemo(() => {
done

2022-11-28 09:13 UTC, foxriver660 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +        <img className="pl-2 pr-10" src={bigCurrencyIcon} />
done

2022-11-28 09:28 UTC, foxriver660 commented on src/components/IngredientCard/IngredientCard.jsx
> +};
done

2022-11-28 09:30 UTC, merged