Month 7/step2
foxriver660/react-burger pull request #3
Opened 2022-11-30 12:16 UTC by foxriver660

2022-12-01 03:18 UTC, ArslanDev666 commented on src/components/App/App.jsx
> +      fetch("https://norma.nomoreparties.space/api/ingredients")
**Надо исправить:**

Добавьте проверку ответа сервера - res.ok:

Например:

```js
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответит не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```js
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2022-12-01 03:36 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Теперь ингредиенты приходят от сервера;

- В приложении есть модальные окна;

- Очень крутая анимация 🔥;

### **Но есть несколько замечаний, которые нужно исправить:**

- Поправьте работу с propTypes (отметил места в коде).

- Поправьте работу с сервером (отметил места в коде).

- Поправьте работу с модальными окнами (отметил места в коде).

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-12-01 03:36 UTC, ArslanDev666 commented on src/components/App/App.jsx
> +          setState({ ...state, hasError: true, isLoading: false });
**Можно лучше**

Вызывать скрытие индикатора загрузки следует в блоке `finally`, а не дублировать в `then` и `catch`
[https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally)

2022-12-01 03:36 UTC, ArslanDev666 commented on src/components/App/App.jsx
> +      fetch("https://norma.nomoreparties.space/api/ingredients")
**Надо исправить**
вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

**Надо исправить:**

Добавьте проверку ответа сервера - res.ok:

Например:

```js
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответит не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```js
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```js
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2022-12-01 03:36 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
>            }}
**Можно лучше:**

возможно лучше будет вынести это в функцию)
А также использовать параметр функции.

```js
const handleClickTab = (tab) => {
  setCurrent(tab);

  switch(tab) {
    case "bun":
      scrollTo(bunRef);
      break;
    //...
  }
}

onClick={handleClickTab}
```

2022-12-01 03:36 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
>          <h2
**Надо исправить:**

не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

```js
{isOpen && (
    компонент открываемого попапа
)}
```

2022-12-01 03:36 UTC, ArslanDev666 commented on src/components/Modal/Modal.jsx
> +const Modal = ({ open, onClose, children }) => {
**Надо исправить:**

не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

```js
{isOpen && (
    компонент открываемого попапа
)}
```

2022-12-01 03:36 UTC, ArslanDev666 commented on src/components/Modal/Modal.jsx
> +  /* eslint-disable*/
**Можно лучше:**

Лучше написать вот так, тогда и eslint ругаться не будет, и ссылка на функцию пересоздаваться не будет.

```js
React.useEffect(() => {
  const escClose = (e) => {
    if (e.key === "Escape") {
      onClose();
    }
  };
  window.addEventListener("keydown", escClose);

  return () => window.removeEventListener("keydown", escClose);
}, [onClose]);
```

2022-12-01 03:36 UTC, ArslanDev666 commented on src/components/Modal/Modal.jsx
> +          onKeyPress={escClose}
**Надо исправить:**

обработчик события по нажатию клавиши должен ставиться только на документ (конечно всегда есть исключения, но это не одно из них).

2022-12-01 03:36 UTC, ArslanDev666 commented on src/components/Modal/Modal.jsx
> +            console.log("click");
**Надо исправить:**

В приложении не должно быть логов.

2022-12-01 03:36 UTC, ArslanDev666 commented on src/components/Modal/Modal.jsx
> +      <ModalOverlay onClose={onClose}>
**Можно лучше:**

у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер.

Ниже показана оптимальная структура модального окна.

```js
<>
  <div className={styles.modal}> {/** ... */} <div>
  <ModalOverlay onClick={onClose} />
</>
```

2022-12-01 03:36 UTC, ArslanDev666 commented on src/components/Modal/Modal.jsx
> +  const element = React.useMemo(() => document.createElement("div"), []);
**Надо исправить:**

Вы же уже создали див для модального окна `modalRootElement`, не совсем понимаю зачем ещё 1 див нужен.

2022-12-01 03:36 UTC, ArslanDev666 commented on src/components/ModalOverlay/ModalOverlay.jsx
> +ModalOverlay.propTypes = {
**Надо исправить:**

Не забывайте указывать `.isRequired`, без этого пропсы не проверяются.

2022-12-01 03:36 UTC, ArslanDev666 commented on src/components/IngredientDetails/IngredientDetails.jsx
> +IngredientDetails.propTypes = {
**Надо исправить:**

Не забывайте указывать `.isRequired`, без этого пропсы не проверяются.

2022-12-01 03:36 UTC, ArslanDev666 commented on src/components/IngredientDetails/IngredientDetails.jsx
> +    <Modal open={open} onClose={onClose}>
**надо исправить:**
Тут и в других компонентах, которые являются контентом для модального окна, не должно содержаться самого модального окна.

Правильный пример использования модального окна.

```js
{open && <Modal onClose={onClose}> <IngredientDetails data={ingredient} /> </Modal>
```

2022-12-01 03:36 UTC, ArslanDev666 commented on src/components/OrderDetails/OrderDetails.jsx
> +    <Modal open={open} onClose={onClose}>
**Надо исправить:**

Похожее замечание есть в `IngredientDetails`.

2022-12-01 09:40 UTC, foxriver660 commented on src/components/App/App.jsx
> +      fetch("https://norma.nomoreparties.space/api/ingredients")
done

2022-12-01 09:56 UTC, foxriver660 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
>            }}
done

2022-12-01 10:11 UTC, foxriver660 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
>          <h2
done

2022-12-01 10:11 UTC, foxriver660 commented on src/components/Modal/Modal.jsx
> +const Modal = ({ open, onClose, children }) => {
done

2022-12-01 10:16 UTC, foxriver660 commented on src/components/Modal/Modal.jsx
> +          onKeyPress={escClose}
done

2022-12-01 10:17 UTC, foxriver660 commented on src/components/Modal/Modal.jsx
> +            console.log("click");
done

2022-12-01 11:04 UTC, foxriver660 commented on src/components/Modal/Modal.jsx
> +      <ModalOverlay onClose={onClose}>
оставил вложенную структуру, так удобнее отцентрировать попап с контентом

2022-12-01 11:07 UTC, foxriver660 commented on src/components/Modal/Modal.jsx
> +  const element = React.useMemo(() => document.createElement("div"), []);
done

2022-12-01 11:08 UTC, foxriver660 commented on src/components/ModalOverlay/ModalOverlay.jsx
> +ModalOverlay.propTypes = {
done

2022-12-01 11:08 UTC, foxriver660 commented on src/components/IngredientDetails/IngredientDetails.jsx
> +IngredientDetails.propTypes = {
done

2022-12-01 11:21 UTC, foxriver660 commented on src/components/IngredientDetails/IngredientDetails.jsx
> +    <Modal open={open} onClose={onClose}>
done

2022-12-01 11:21 UTC, foxriver660 commented on src/components/OrderDetails/OrderDetails.jsx
> +    <Modal open={open} onClose={onClose}>
done

2022-12-01 11:22 UTC, foxriver660 commented on src/components/Modal/Modal.jsx
> +  /* eslint-disable*/
done

2022-12-01 12:52 UTC, foxriver660 commented on src/components/App/App.jsx
> +          setState({ ...state, hasError: true, isLoading: false });
при добавлении блока finally с setState`({ ...state, isLoading: false})`, страница не рендерится, массив state.data остается пустым

2022-12-02 03:10 UTC, ArslanDev666 commented on src/components/App/App.jsx
> +          setState({ ...state, hasError: true, isLoading: false });
Думаю тут поможет функциональное обновление. https://reactjs.org/docs/hooks-reference.html#functional-updates

2022-12-02 03:24 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодец! Работа принята 🔥, удачи в дальнейшем обучении!**

- Все замечания с прошлого ревью были исправлены.

### **Сделает код лучше:**

- Заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

2022-12-02 03:24 UTC, ArslanDev666 commented on src/components/App/App.jsx
> +  /* eslint-disable */
**Можно лучше:** 

Используйте функциональное обновление зависимостей, тогда и eslint ругаться не будет)

2022-12-02 03:24 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +      )}
**Надо исправить:**

Данный функционал сейчас излишен, т.к. в следующих спринтах, вы будете реализовывать DnD (drag & drop). И пользователю нужно будет перетаскивать ингредиенты.

2022-12-02 08:36 UTC, merged