Month 9/step 2
foxriver660/react-burger pull request #7
Opened 2023-02-11 14:05 UTC by foxriver660

2023-02-11 15:06 UTC, andryxxa93 requested changes
Отличный проект!
Что понравилось:
- На каждый обработчик сокета создан экшен.
- Сокет открывается и закрывается точно согласно требованиям брифа.
- Реализовано ранее получение номера заказа через сокет. 

Что необходимо исправить:
- Необходимо добавить проверку на тот случай если токен протух и его необходимо обновить. Сообщение об ошибке будет содержаться в поле message с таким текстом - 'Invalid or missing token'. Так же хорошо бы добавить таймер на повторное переподключение к сокету, чтобы в случае ошибки не было много "холостых" попыток соединиться.

**Можно лучше**
- Нужно рассматривать разный набор экшенов при работе с сокетом для авторизованного и неавторизованного пользователя, и задавать свой набор экшенов как аргумент при вызовах миддлвара wsMiddleware в configureStore.

 - Нужно организовать раздельное хранение данных в хранилище Redux, получаемых от сокета для авторизованного и неавторизованного пользователей.

Удачных правок!

2023-02-11 15:06 UTC, andryxxa93 commented on src/middlewares/socet-middleware.js
> +        socket.onmessage = (event) => {
**Необходимо исправить**
Необходимо добавить проверку на тот случай если токен протух и его необходимо обновить. Сообщение об ошибке будет содержаться в поле `message` с таким текстом - '`Invalid or missing token'. `Так же хорошо бы добавить таймер на повторное переподключение к сокету, чтобы в случае ошибки не было много "холостых" попыток соединиться.

2023-02-11 15:27 UTC, andryxxa93 commented
Прошу прощения -  на замечание насчет организации разных наборов экшенов для авторизованных и не авторизованных пользователей не обращайте внимание - у вас всё верно.

2023-02-12 13:19 UTC, foxriver660 commented on src/middlewares/socet-middleware.js
> +        socket.onmessage = (event) => {
done

2023-02-12 15:03 UTC, andryxxa93 approved these changes
Отлично! Вы хорошо потрудились. Понравилось, что сообщением об ошибке поместили в константу и добавили таймер для переподключения. Так держать! Работа принята. Удачи и успехов в дальнейшем!

2023-03-12 15:43 UTC, merged